# Generated by Django 3.2.13 on 2022-08-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_file_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='usercsv',
        ),
    ]
