# Generated by Django 3.2.13 on 2022-08-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_user_usercsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.DeleteModel(
            name='temp',
        ),
        migrations.DeleteModel(
            name='file',
        ),
    ]
